# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_THEAD_CLK) += \
	clk.o

obj-$(CONFIG_CLK_THEAD_TH1520_AP) += clk-th1520-ap.o
obj-$(CONFIG_CLK_TH1520_FM)  += clk-th1520-fm.o
obj-$(CONFIG_CLK_TH1520_FM)  += gate/
